R2P2_USB_DEVICE ?= 1
R2P2_TINYUSB ?= 1
R2P2_USB_CDC ?= 1
R2P2_USB_CDC_CONSOLE_ENABLED_DEFAULT ?= 1
R2P2_USB_CDC_DATA_ENABLED_DEFAULT ?= 1
R2P2_USB_MSC ?= 0
R2P2_USB_HID ?= 0
R2P2_USB_MIDI ?= 0
R2P2_USB_VENDOR ?= 0
R2P2_USB_VIDEO ?= 0

CFLAGS += -DR2P2_USB_DEVICE=$(R2P2_USB_DEVICE)
CFLAGS += -DR2P2_TINYUSB=$(R2P2_TINYUSB)
CFLAGS += -DR2P2_USB_CDC=$(R2P2_USB_CDC)
CFLAGS += -DR2P2_USB_CDC_CONSOLE_ENABLED_DEFAULT=$(R2P2_USB_CDC_CONSOLE_ENABLED_DEFAULT)
CFLAGS += -DR2P2_USB_CDC_DATA_ENABLED_DEFAULT=$(R2P2_USB_CDC_DATA_ENABLED_DEFAULT)
CFLAGS += -DR2P2_USB_MSC=$(R2P2_USB_MSC)
CFLAGS += -DR2P2_USB_HID=$(R2P2_USB_HID)
CFLAGS += -DR2P2_USB_MIDI=$(R2P2_USB_MIDI)
CFLAGS += -DR2P2_USB_VENDOR=$(R2P2_USB_VENDOR)
CFLAGS += -DR2P2_USB_VIDEO=$(R2P2_USB_VIDEO)

SRC_SUPERVISOR += \
	supervisor/shared/serial.c \
	supervisor/shared/usb/usb.c \
	supervisor/shared/usb/usb_desc.c \
	supervisor/shared/usb/usb_device.c

SRC_MOD += \
	shared-module/usb_cdc/__init__.c
