#ifndef R2P2_RUNTIME_CONFIG_H
#define R2P2_RUNTIME_CONFIG_H

#ifndef R2P2_TINYUSB
#define R2P2_TINYUSB 1
#endif

#ifndef R2P2_USB_DEVICE
#define R2P2_USB_DEVICE 1
#endif

#ifndef R2P2_USB_DEVICE_INSTANCE
#define R2P2_USB_DEVICE_INSTANCE 0
#endif

#ifndef R2P2_USB_DEVICE_HIGH_SPEED
#define R2P2_USB_DEVICE_HIGH_SPEED 0
#endif

#ifndef R2P2_USB_CDC
#define R2P2_USB_CDC 1
#endif

#ifndef R2P2_USB_CDC_CONSOLE_ENABLED_DEFAULT
#define R2P2_USB_CDC_CONSOLE_ENABLED_DEFAULT 1
#endif

#ifndef R2P2_USB_CDC_DATA_ENABLED_DEFAULT
#define R2P2_USB_CDC_DATA_ENABLED_DEFAULT 1
#endif

#ifndef R2P2_USB_MSC
#define R2P2_USB_MSC 0
#endif

#ifndef R2P2_USB_HID
#define R2P2_USB_HID 0
#endif

#ifndef R2P2_USB_MIDI
#define R2P2_USB_MIDI 0
#endif

#ifndef R2P2_USB_VENDOR
#define R2P2_USB_VENDOR 0
#endif

#ifndef R2P2_USB_VIDEO
#define R2P2_USB_VIDEO 0
#endif

#ifndef R2P2_PORT_SERIAL
#define R2P2_PORT_SERIAL 0
#endif

#ifndef R2P2_USB_KEYBOARD_WORKFLOW
#define R2P2_USB_KEYBOARD_WORKFLOW 0
#endif

#ifndef R2P2_DEBUG_TINYUSB
#define R2P2_DEBUG_TINYUSB 0
#endif

#ifndef R2P2_MAX3421E
#define R2P2_MAX3421E 0
#endif

#ifndef R2P2_USB_HOST
#define R2P2_USB_HOST 0
#endif

#ifndef R2P2_USB_HOST_INSTANCE
#define R2P2_USB_HOST_INSTANCE 1
#endif

#ifndef R2P2_TUSB_ATTR_USBRAM
#define R2P2_TUSB_ATTR_USBRAM ".bss.usbram"
#endif

#ifndef R2P2_TUSB_MEM_ALIGN
#define R2P2_TUSB_MEM_ALIGN 4
#endif

#endif
