#ifndef R2P2_CONFIG_H
#define R2P2_CONFIG_H

#ifndef R2P2_TINYUSB
#define R2P2_TINYUSB 1
#endif

#ifndef R2P2_USB_DEVICE
#define R2P2_USB_DEVICE 1
#endif

#ifndef R2P2_USB_DEVICE_INSTANCE
#define R2P2_USB_DEVICE_INSTANCE 0
#endif

#ifndef R2P2_USB_DEVICE_HIGH_SPEED
#define R2P2_USB_DEVICE_HIGH_SPEED 0
#endif

#ifndef R2P2_USB_CDC
#define R2P2_USB_CDC 1
#endif

#ifndef R2P2_USB_CDC_CONSOLE_ENABLED_DEFAULT
#define R2P2_USB_CDC_CONSOLE_ENABLED_DEFAULT 1
#endif

#ifndef R2P2_USB_CDC_DATA_ENABLED_DEFAULT
#define R2P2_USB_CDC_DATA_ENABLED_DEFAULT 1
#endif

#ifndef R2P2_USB_MSC
#define R2P2_USB_MSC 0
#endif

#ifndef R2P2_USB_HID
#define R2P2_USB_HID 0
#endif

#ifndef R2P2_USB_MIDI
#define R2P2_USB_MIDI 0
#endif

#ifndef R2P2_DEBUG_TINYUSB
#define R2P2_DEBUG_TINYUSB 0
#endif

#ifndef R2P2_TUSB_ATTR_USBRAM
#define R2P2_TUSB_ATTR_USBRAM ".bss.usbram"
#endif

#ifndef R2P2_TUSB_MEM_ALIGN
#define R2P2_TUSB_MEM_ALIGN 4
#endif

#ifndef R2P2_USB_VENDOR_ID
#define R2P2_USB_VENDOR_ID 0x16c0
#endif

#ifndef R2P2_USB_PRODUCT_ID
#define R2P2_USB_PRODUCT_ID 0x27dd
#endif

#ifndef R2P2_USB_MANUFACTURER
#define R2P2_USB_MANUFACTURER "R2P2"
#endif

#ifndef R2P2_USB_PRODUCT
#define R2P2_USB_PRODUCT "R2P2 nRF52"
#endif

#ifndef R2P2_USB_INTERFACE_NAME
#define R2P2_USB_INTERFACE_NAME "R2P2"
#endif

#ifndef R2P2_USB_NUM_ENDPOINT_PAIRS
#define R2P2_USB_NUM_ENDPOINT_PAIRS 8
#endif

#ifndef R2P2_USB_NUM_IN_ENDPOINTS
#define R2P2_USB_NUM_IN_ENDPOINTS 8
#endif

#ifndef R2P2_USB_NUM_OUT_ENDPOINTS
#define R2P2_USB_NUM_OUT_ENDPOINTS 8
#endif

#define R2P2_USB_CDC0_EP_NOTIFICATION 0x81
#define R2P2_USB_CDC0_EP_OUT 0x02
#define R2P2_USB_CDC0_EP_IN 0x83
#define R2P2_USB_CDC1_EP_NOTIFICATION 0x84
#define R2P2_USB_CDC1_EP_OUT 0x05
#define R2P2_USB_CDC1_EP_IN 0x86

#endif
