#ifndef R2P2_NRF52_SDK_CONFIG_WRAPPER_H
#define R2P2_NRF52_SDK_CONFIG_WRAPPER_H

#include "r2p2_config.h"

#define APP_USBD_VID R2P2_USB_VENDOR_ID
#define APP_USBD_PID R2P2_USB_PRODUCT_ID
#define APP_USBD_STRING_ID_MANUFACTURER 1
#define APP_USBD_STRINGS_MANUFACTURER APP_USBD_STRING_DESC(R2P2_USB_MANUFACTURER)
#define APP_USBD_STRING_ID_PRODUCT 2
#define APP_USBD_STRINGS_PRODUCT APP_USBD_STRING_DESC(R2P2_USB_PRODUCT)
#define APP_USBD_STRING_ID_SERIAL 3
#define APP_USBD_STRING_SERIAL_EXTERN 1
#define APP_USBD_STRING_ID_CONFIGURATION 4
#define APP_USBD_STRINGS_CONFIGURATION APP_USBD_STRING_DESC(R2P2_USB_CONFIGURATION)
#define APP_USBD_CONFIG_SELF_POWERED R2P2_USB_SELF_POWERED
#define APP_USBD_CONFIG_MAX_POWER R2P2_USB_MAX_POWER_MA

#include_next "sdk_config.h"

#endif
